# Generated by Django 4.2.11 on 2024-10-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_fuentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente',
            name='fecha_publicacion',
        ),
    ]
