# Generated by Django 4.2.11 on 2024-10-26 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_fuentes', '0002_remove_fuente_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='etiqueta',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
