# Generated by Django 4.2.11 on 2024-10-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_fuentes', '0003_fuente_etiqueta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='etiqueta',
            new_name='etiquetas',
        ),
    ]
