# Generated by Django 4.2.11 on 2024-11-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_entrada/')),
                ('texto_procesado', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_referencia', models.FileField(blank=True, null=True, upload_to='plantillas_referencia/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_resultado', models.FileField(upload_to='documentos_generados/')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('LATEX', 'LaTeX')], default='PDF', max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantillas.archivoentrada')),
                ('plantilla_usada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantillas.plantilla')),
            ],
        ),
    ]
